config/routes.rb
Wiyomi::Application.routes.draw do
  root to: 'root#index'
  get 'savethedate', to: 'root#savethedate'
  resources :responses, only: [:index, :create]
end

app/models/response.rb
class Response
  include Mongoid::Document
	include Mongoid::Timestamps
	
  field :name, type: String
  field :percentage, type: Integer

  
  validates :name, :percentage, presence: true
  
  before_save ->{ self.name = self.name.squish.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
	def index
		@responses = Response.all.to_a
		render json: @responses
	end
	
	def create 
		@response = Response.new(response_params)
		if @response.save
			render json: @response
		else 
			head :unprocessable_entity
		end
	end

	private

	def response_params
		params.require(:response).permit(:name, :percentage)
	end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
		redirect_to :savethedate
  end
  
  def savethedate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wiyomi !</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Wiyomi! </title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>

app/views/root/index.html.erb
<div id="page-content">
  <div id="plane"
    data-0="opacity: 1;"
    data-50p="transform: scale(.25) rotate(0deg); left: 25%;"
    data-100p="left: 50%;"
    data-250p="transform: scale(.25) rotate(720deg);"
    data-290p="opacity: 0">
    <img src="<%= asset_path 'plane.png' %>">
  </div>

    <div id="cloud1" class="drop"
      data-150p="opacity: 0; top: 0%"
      data-250p="opacity: 1; top: 45%"
      data-300p="opacity: 0;">
      <img src="<%= asset_path 'cloud.png' %>">
    </div>

    <div id="cloud2" class="drop"
      data-0="top:70%;"
      data-150p="opacity: 0; top: 60%;"
      data-175p="opacity: 1; top: 10%"
      data-215p="opacity: 0;">
      <img src="<%= asset_path 'cloud.png' %>">
    </div>

    <div id="cloud3" class="drop"
      data-150p="opacity: 0; top: 10%"
      data-200p="opacity: 1; top: 60%"
      data-250p="opacity: 0;">
      <img src="<%= asset_path 'cloud.png' %>">
    </div>

    <div id="scroll" class="animated bounce"
      data-0="opacity:1"
      data-40p= "opacity: 0">
      <span>↓</span>
    </div>
  <div id="slides-container">

    <div id="slides"
      data-0="transform: translate(0%,0%)"
      data-150p="transform: translate(-50%,0%)"
      data-200p=""
      data-350p="transform: translate(-100%,0%)"
      data-450p="">
    <div id="slide-1" class="slide">
    </div>
      <div id="slide-2" class="slide">
        </div>
      <div id="slide-3" class="slide">
    </div>
    </div>

    <div id="post"
      data-355p="top: -30%;"
      data-365p="top: 75%; display: block">
      <img src="<%= asset_path 'post.png' %>">
    </div>

    <div id="couple"
      data-370p="transform[bounce]: translateY(-20%);"
      data-375p="transform[bounce]: translateY(80%)"
      data-385p="transform[bounce]: translateY(70%)"
      data-390p="transform[bounce]: translateY(80%)">
        <img src="<%= asset_path 'couple.png' %>">
    </div>

    <div id="guests"
      data-395p="transform[bounce]: translateY(-20%);"
      data-400p="transform[bounce]: translateY(80%)"
      data-410p="transform[bounce]: translateY(70%)"
      data-415p="transform[bounce]: translateY(80%)"
    >
      <img src="<%= asset_path 'guests.png' %>">
    </div>

    <div id="announcement"
      data-390p="opacity: 0;"
      data-410p="opacity: 1"
    >
      <h1>Come and Join Us in Celebrating Our Marriage!</h1>
      <p>April 8 - April 12, 2015</p>
      <p>Lahaina, HI</p>
      <p>**More Information to Follow**</p>
    </div>


   </div>
<div class="helper"></div>

</div>
<script type="text/javascript">
  var s = skrollr.init();
</script>

app/views/root/savethedate.html.erb
<div id="page-content">
  <div id="plane"
    data-0="opacity: 1; top: 30%;"
    data-50p="transform: rotate(0deg); left: 25%;"
    data-100p="left: 50%;"
    data-250p="transform: rotate(720deg);"
    data-290p="opacity: 0">
    <img src="<%= asset_path 'plane.png' %>">
  </div>

    <div id="cloud1" class="drop"
      data-150p="opacity: 0; top: 0%"
      data-250p="opacity: 1; top: 45%"
      data-300p="opacity: 0;">
      <img src="<%= asset_path 'cloud.png' %>">
    </div>

    <div id="cloud2" class="drop"
      data-0="top:70%;"
      data-150p="opacity: 0; top: 60%;"
      data-175p="opacity: 1; top: 10%"
      data-215p="opacity: 0;">
      <img src="<%= asset_path 'cloud.png' %>">
    </div>

    <div id="cloud3" class="drop"
      data-150p="opacity: 0; top: 10%"
      data-200p="opacity: 1; top: 60%"
      data-250p="opacity: 0;">
      <img src="<%= asset_path 'cloud.png' %>">
    </div>

    <div id="scroll" class="animated bounce"
      data-0="opacity:1"
      data-40p= "opacity: 0">
      <span>↓</span>
    </div>
  <div id="slides-container">

    <div id="slides"
      data-0="transform: translate(0%,0%)"
      data-150p="transform: translate(-50%,0%)"
      data-200p=""
      data-350p="transform: translate(-100%,0%)"
      data-450p="">
    <div id="slide-1" class="slide">
    </div>
      <div id="slide-2" class="slide">
        </div>
      <div id="slide-3" class="slide">
    </div>
    </div>

    <div id="post"
      data-355p="top: -30%;"
      data-365p="top: 75%; display: block">
      <img src="<%= asset_path 'post.png' %>">
    </div>

    <div id="couple"
      data-370p="transform[bounce]: translateY(-20%);"
      data-375p="transform[bounce]: translateY(80%)"
      data-385p="transform[bounce]: translateY(70%)"
      data-390p="transform[bounce]: translateY(80%)">
        <img src="<%= asset_path 'couple.png' %>">
    </div>

    <div id="guests"
      data-395p="transform[bounce]: translateY(-20%);"
      data-400p="transform[bounce]: translateY(75%)"
      data-410p="transform[bounce]: translateY(70%)"
      data-415p="transform[bounce]: translateY(75%)"
    >
      <img src="<%= asset_path 'guests.png' %>">
    </div>

    <div id="announcement"
      data-390p="opacity: 0;"
      data-410p="opacity: 1"
    >
      <h1>Come and Join Us in Celebrating Our Marriage!</h1>
      <p>April 8 - April 12, 2015</p>
      <p>Lahaina (Maui), HI</p>
      <p>**More Information to Follow**</p>
      <form action="<%= responses_url %>" method="POST">
				<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
				<label for="response_name">Full Name: </label>
				<input type="text" id="response_name" name="response[name]" required><br>
				<label for="response_percentage">How likely is it that you can come?</label>
				<select id="response_percentage" name="response[percentage]">
					<option value="10">10%</option>
					<option value="20">20%</option>
					<option value="30">30%</option>
					<option value="40">40%</option>
					<option value="50" selected>50%</option>
					<option value="60">60%</option>
					<option value="70">70%</option>
					<option value="80">80%</option>
					<option value="90">90%</option>
					<option value="100">100%</option>
				</select><br>
				<input type="submit" value="Submit">
			</form>
    </div>


   </div>
<div class="helper"></div>

</div>
<script type="text/javascript">
  var s = skrollr.init();
</script>